<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder_en extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menu')->insert(['id' => 0, 'name_' => 'Home', 'display_name' => 'Home', 'menu_dad_id' => -99, 'link_command' => '#', 'tooltip' => 'Home', 'image_icon' => 'fas fa-home fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 1000, 'name_' => 'Manage_your_Account', 'display_name' => 'Manage your Account', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Manage your Account', 'image_icon' => 'fas fa-key fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 1001, 'name_' => 'Personal_information', 'display_name' => 'Personal information', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Personal_information', 'tooltip' => 'Manage your Account', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Manage your Account / Personal information', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 1002, 'name_' => 'Data_and_Privacy', 'display_name' => 'Data and Privacy', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Data_and_Privacy', 'tooltip' => 'Manage your Account', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Manage your Account / Data and Privacy', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 1003, 'name_' => 'Notifications_and_Alerts', 'display_name' => 'Notifications and Alerts', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Notifications_and_Alerts', 'tooltip' => 'Manage your Account', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Manage your Account / Notifications and Alerts', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 1004, 'name_' => 'Change_of_password', 'display_name' => 'Change of password', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Change_of_password', 'tooltip' => 'Manage your Account', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Manage your Account / Change of password', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2000, 'name_' => 'Security_options', 'display_name' => 'Security options', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Security options', 'image_icon' => 'fas fa-unlock-alt fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 2001, 'name_' => 'Application_Menu', 'display_name' => 'Application Menu', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/Application_Menu', 'tooltip' => 'Security options', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Security options / Application Menu', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2002, 'name_' => 'Application_Features', 'display_name' => 'Application Features', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/Application_Features', 'tooltip' => 'Security options', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Security options / Application Features', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2003, 'name_' => 'System_Users', 'display_name' => 'System Users', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/System_Users', 'tooltip' => 'Security options', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Security options / System Users', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2004, 'name_' => 'File_Storage', 'display_name' => 'File Storage', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/File_Storage', 'tooltip' => 'Security options', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Security options / File Storage', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3000, 'name_' => 'Parameterization', 'display_name' => 'Parameterization', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Parameterization', 'image_icon' => 'fas fa-clipboard-list fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 3001, 'name_' => 'Sports', 'display_name' => 'Sports', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Sports', 'tooltip' => 'Parameterization', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parameterization / Sports', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3002, 'name_' => 'Sports_venues', 'display_name' => 'Sports venues', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Sports_venues', 'tooltip' => 'Parameterization', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parameterization / Sports venues', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3003, 'name_' => 'Types_of_trainers', 'display_name' => 'Types of trainers', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Types_of_trainers', 'tooltip' => 'Parameterization', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parameterization / Types of trainers', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3004, 'name_' => 'Sports_modalities', 'display_name' => 'Sports modalities', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Sports_modalities', 'tooltip' => 'Parameterization', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parameterization / Sports modalities', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3005, 'name_' => 'Categories', 'display_name' => 'Categories', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Categories', 'tooltip' => 'Parameterization', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parameterization / Categories', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4000, 'name_' => 'Administrative_Management', 'display_name' => 'Administrative Management', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Administrative Management', 'image_icon' => 'fas fa-chart-line fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 4001, 'name_' => 'Athletes', 'display_name' => 'Athletes', 'menu_dad_id' => 4000, 'link_command' => '#', 'tooltip' => 'Administrative Management', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 4002, 'name_' => 'Registration', 'display_name' => 'Registration', 'menu_dad_id' => 4001, 'link_command' => 'app/Administrative_Management/Athletes/Registration', 'tooltip' => 'Administrative Management', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrative Management / Athletes / Registration', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4003, 'name_' => 'Payments_and_reconciliation', 'display_name' => 'Payments and reconciliation', 'menu_dad_id' => 4001, 'link_command' => 'app/Administrative_Management/Registration/Payments_and_reconciliation', 'tooltip' => 'Administrative Management', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrative Management / Registration / Payments and reconciliation', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4004, 'name_' => 'Trainers', 'display_name' => 'Trainers', 'menu_dad_id' => 4000, 'link_command' => '#', 'tooltip' => 'Administrative Management', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 4005, 'name_' => 'Trainer_registry', 'display_name' => 'Trainer registry', 'menu_dad_id' => 4004, 'link_command' => 'app/Administrative_Management/Trainers/Trainer_registry', 'tooltip' => 'Administrative Management', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrative Management / Trainers / Trainer registry', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4006, 'name_' => 'Plan_assignment', 'display_name' => 'Plan assignment', 'menu_dad_id' => 4004, 'link_command' => 'app/Administrative_Management/Trainer registry/Plan_assignment', 'tooltip' => 'Administrative Management', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrative Management / Trainer registry / Plan assignment', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5000, 'name_' => 'Inventory', 'display_name' => 'Inventory', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Inventory', 'image_icon' => 'fas fa-dolly fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 5001, 'name_' => 'Implements', 'display_name' => 'Implements', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Implements', 'tooltip' => 'Inventory', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventory / Implements', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5002, 'name_' => 'Sports_clothing', 'display_name' => 'Sports clothing', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Sports_clothing', 'tooltip' => 'Inventory', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventory / Sports clothing', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5003, 'name_' => 'Allocation_by_scenario', 'display_name' => 'Allocation by scenario', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Allocation_by_scenario', 'tooltip' => 'Inventory', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventory / Allocation by scenario', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5004, 'name_' => 'Tournaments_and_events', 'display_name' => 'Tournaments and events', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Tournaments_and_events', 'tooltip' => 'Inventory', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventory / Tournaments and events', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 6000, 'name_' => 'Training', 'display_name' => 'Training', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Training', 'image_icon' => 'fas fa-award fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 6001, 'name_' => 'Training_plans', 'display_name' => 'Training plans', 'menu_dad_id' => 6000, 'link_command' => 'app/Training/Training_plans', 'tooltip' => 'Training', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Training / Training plans', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 6002, 'name_' => 'Evaluation_and_performance', 'display_name' => 'Evaluation and performance', 'menu_dad_id' => 6000, 'link_command' => 'app/Training/Evaluation_and_performance', 'tooltip' => 'Training', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Training / Evaluation and performance', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 7000, 'name_' => 'Athletes_and_parents', 'display_name' => 'Athletes and parents', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Athletes and parents', 'image_icon' => 'fas fa-users fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 7001, 'name_' => 'Scheduled_training', 'display_name' => 'Scheduled training', 'menu_dad_id' => 7000, 'link_command' => 'app/Athletes_and_parents/Scheduled_training', 'tooltip' => 'Athletes and parents', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Athletes and parents / Scheduled training', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 7002, 'name_' => 'Results_and_reports', 'display_name' => 'Results and reports', 'menu_dad_id' => 7000, 'link_command' => 'app/Athletes_and_parents/Results_and_reports', 'tooltip' => 'Athletes and parents', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Athletes and parents / Results and reports', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 7003, 'name_' => 'PQRS_registration', 'display_name' => 'PQRS registration', 'menu_dad_id' => 7000, 'link_command' => 'app/Athletes_and_parents/PQRS_registration', 'tooltip' => 'Athletes and parents', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Athletes and parents / PQRS registration', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 8000, 'name_' => 'Events_calendar', 'display_name' => 'Events calendar', 'menu_dad_id' => 0, 'link_command' => 'app/Athletes_and_parents/Events_calendar', 'tooltip' => 'Events calendar', 'image_icon' => 'fas fa-calendar-alt fa-fw', 'status_id' => 1, 'breadcrumb' => 'Athletes and parents / Events calendar', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9000, 'name_' => 'Reports', 'display_name' => 'Reports', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Reports', 'image_icon' => 'fas fa-file-download fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 9001, 'name_' => 'Report_1', 'display_name' => 'Report 1', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_1', 'tooltip' => 'Reports', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reports / Report 1', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9002, 'name_' => 'Report_2', 'display_name' => 'Report 2', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_2', 'tooltip' => 'Reports', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reports / Report 2', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9003, 'name_' => 'Report_3', 'display_name' => 'Report 3', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_3', 'tooltip' => 'Reports', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reports / Report 3', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9004, 'name_' => 'Report_4', 'display_name' => 'Report 4', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_4', 'tooltip' => 'Reports', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reports / Report 4', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9005, 'name_' => 'Report_5', 'display_name' => 'Report 5', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_5', 'tooltip' => 'Reports', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reports / Report 5', 'menu_type_id' => 2]);
    }
}
