<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder_es extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menu')->insert(['id' => 0, 'name_' => 'Home', 'display_name' => 'Inicio', 'menu_dad_id' => -99, 'link_command' => '#', 'tooltip' => 'Inicio', 'image_icon' => 'fas fa-home fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 1000, 'name_' => 'Manage_your_Account', 'display_name' => 'Administrar tu Cuenta', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Administrar tu Cuenta', 'image_icon' => 'fas fa-key fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 1001, 'name_' => 'Personal_information', 'display_name' => 'Información Personal', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Personal_information', 'tooltip' => 'Administrar tu Cuenta', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrar tu Cuenta / Información Personal', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 1002, 'name_' => 'Data_and_Privacy', 'display_name' => 'Datos y Privacidad', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Data_and_Privacy', 'tooltip' => 'Administrar tu Cuenta', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrar tu Cuenta / Datos y Privacidad', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 1003, 'name_' => 'Notifications_and_Alerts', 'display_name' => 'Notificaciones y Alertas', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Notifications_and_Alerts', 'tooltip' => 'Administrar tu Cuenta', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrar tu Cuenta / Notificaciones y Alertas', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 1004, 'name_' => 'Change_of_password', 'display_name' => 'Cambio de Contraseña', 'menu_dad_id' => 1000, 'link_command' => 'app/Manage_your_Account/Change_of_password', 'tooltip' => 'Administrar tu Cuenta', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Administrar tu Cuenta / Cambio de Contraseña', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2000, 'name_' => 'Security_options', 'display_name' => 'Opciones de Seguridad', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Opciones de Seguridad', 'image_icon' => 'fas fa-unlock-alt fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 2001, 'name_' => 'Application_Menu', 'display_name' => 'Menú de Aplicación', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/Application_Menu', 'tooltip' => 'Opciones de Seguridad', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Opciones de Seguridad / Menú de Aplicación', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2002, 'name_' => 'Application_Features', 'display_name' => 'Roles de Aplicación', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/Application_Features', 'tooltip' => 'Opciones de Seguridad', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Opciones de Seguridad / Roles de Aplicación', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2003, 'name_' => 'System_Users', 'display_name' => 'Usuarios del Sistema', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/System_Users', 'tooltip' => 'Opciones de Seguridad', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Opciones de Seguridad / Usuarios del Sistema', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 2004, 'name_' => 'File_Storage', 'display_name' => 'Clubes Deportivos', 'menu_dad_id' => 2000, 'link_command' => 'app/Security_options/File_Storage', 'tooltip' => 'Opciones de Seguridad', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Opciones de Seguridad / Clubes Deportivos', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3000, 'name_' => 'Parameterization', 'display_name' => 'Parametrización', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Parametrización', 'image_icon' => 'fas fa-clipboard-list fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 3001, 'name_' => 'Sports', 'display_name' => 'Deportes', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Sports', 'tooltip' => 'Parametrización', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parametrización / Deportes', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3002, 'name_' => 'Sports_venues', 'display_name' => 'Escenarios Deportivos', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Sports_venues', 'tooltip' => 'Parametrización', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parametrización / Escenarios Deportivos', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3003, 'name_' => 'Types_of_trainers', 'display_name' => 'Tipos de Formadores', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Types_of_trainers', 'tooltip' => 'Parametrización', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parametrización / Tipos de Formadores', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3004, 'name_' => 'Sports_modalities', 'display_name' => 'Modalidades Deportivas', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Sports_modalities', 'tooltip' => 'Parametrización', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parametrización / Modalidades Deportivas', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 3005, 'name_' => 'Categories', 'display_name' => 'Categorías', 'menu_dad_id' => 3000, 'link_command' => 'app/Parameterization/Categories', 'tooltip' => 'Parametrización', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Parametrización / Categorías', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4000, 'name_' => 'Administrative_Management', 'display_name' => 'Gestión Administrativa', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Gestión Administrativa', 'image_icon' => 'fas fa-chart-line fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 4001, 'name_' => 'Athletes', 'display_name' => 'Deportistas', 'menu_dad_id' => 4000, 'link_command' => '#', 'tooltip' => 'Gestión Administrativa', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 4002, 'name_' => 'Registration', 'display_name' => 'Inscripción', 'menu_dad_id' => 4001, 'link_command' => 'app/Administrative_Management/Athletes/Registration', 'tooltip' => 'Gestión Administrativa', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Gestión Administrativa / Deportistas / Inscripción', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4003, 'name_' => 'Payments_and_reconciliation', 'display_name' => 'Pagos y Conciliación', 'menu_dad_id' => 4001, 'link_command' => 'app/Administrative_Management/Registration/Payments_and_reconciliation', 'tooltip' => 'Gestión Administrativa', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Gestión Administrativa / Inscripción / Pagos y Conciliación', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4004, 'name_' => 'Trainers', 'display_name' => 'Formadores', 'menu_dad_id' => 4000, 'link_command' => '#', 'tooltip' => 'Gestión Administrativa', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 4005, 'name_' => 'Trainer_registry', 'display_name' => 'Registro de Formadores', 'menu_dad_id' => 4004, 'link_command' => 'app/Administrative_Management/Trainers/Trainer_registry', 'tooltip' => 'Gestión Administrativa', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Gestión Administrativa / Formadores / Registro de Formadores', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 4006, 'name_' => 'Plan_assignment', 'display_name' => 'Asignación de Plan', 'menu_dad_id' => 4004, 'link_command' => 'app/Administrative_Management/Trainer registry/Plan_assignment', 'tooltip' => 'Gestión Administrativa', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Gestión Administrativa / Registro de Formadores / Asignación de Plan', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5000, 'name_' => 'Inventory', 'display_name' => 'Inventario', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Inventario', 'image_icon' => 'fas fa-dolly fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 5001, 'name_' => 'Implements', 'display_name' => 'Implementos', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Implements', 'tooltip' => 'Inventario', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventario / Implementos', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5002, 'name_' => 'Sports_clothing', 'display_name' => 'Indumentaria Deportiva', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Sports_clothing', 'tooltip' => 'Inventario', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventario / Indumentaria Deportiva', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5003, 'name_' => 'Allocation_by_scenario', 'display_name' => 'Asignación por Escenario', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Allocation_by_scenario', 'tooltip' => 'Inventario', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventario / Asignación por Escenario', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 5004, 'name_' => 'Tournaments_and_events', 'display_name' => 'Torneos y Eventos', 'menu_dad_id' => 5000, 'link_command' => 'app/Inventory/Tournaments_and_events', 'tooltip' => 'Inventario', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Inventario / Torneos y Eventos', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 6000, 'name_' => 'Training', 'display_name' => 'Formación', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Formación', 'image_icon' => 'fas fa-award fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 6001, 'name_' => 'Training_plans', 'display_name' => 'Planes de Entreno', 'menu_dad_id' => 6000, 'link_command' => 'app/Training/Training_plans', 'tooltip' => 'Formación', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Formación / Planes de Entreno', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 6002, 'name_' => 'Evaluation_and_performance', 'display_name' => 'Evaluación y Desempeño', 'menu_dad_id' => 6000, 'link_command' => 'app/Training/Evaluation_and_performance', 'tooltip' => 'Formación', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Formación / Evaluación y Desempeño', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 7000, 'name_' => 'Athletes_and_parents', 'display_name' => 'Deportistas y Padres', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Deportistas y Padres', 'image_icon' => 'fas fa-users fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 7001, 'name_' => 'Scheduled_training', 'display_name' => 'Entrenos Programados', 'menu_dad_id' => 7000, 'link_command' => 'app/Athletes_and_parents/Scheduled_training', 'tooltip' => 'Deportistas y Padres', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Deportistas y Padres / Entrenos Programados', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 7002, 'name_' => 'Results_and_reports', 'display_name' => 'Resultados e Informes', 'menu_dad_id' => 7000, 'link_command' => 'app/Athletes_and_parents/Results_and_reports', 'tooltip' => 'Deportistas y Padres', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Deportistas y Padres / Resultados e Informes', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 7003, 'name_' => 'PQRS_registration', 'display_name' => 'Registro de PQRS', 'menu_dad_id' => 7000, 'link_command' => 'app/Athletes_and_parents/PQRS_registration', 'tooltip' => 'Deportistas y Padres', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Deportistas y Padres / Registro de PQRS', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 8000, 'name_' => 'Events_calendar', 'display_name' => 'Calendario de Eventos', 'menu_dad_id' => 0, 'link_command' => 'app/Athletes_and_parents/Events_calendar', 'tooltip' => 'Calendario de Eventos', 'image_icon' => 'fas fa-calendar-alt fa-fw', 'status_id' => 1, 'breadcrumb' => 'Deportistas y Padres / Calendario de Eventos', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9000, 'name_' => 'Reports', 'display_name' => 'Reportes', 'menu_dad_id' => 0, 'link_command' => '#', 'tooltip' => 'Reportes', 'image_icon' => 'fas fa-file-download fa-fw', 'status_id' => 1, 'breadcrumb' => '', 'menu_type_id' => 1]);
        DB::table('menu')->insert(['id' => 9001, 'name_' => 'Report_1', 'display_name' => 'Reporte 1', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_1', 'tooltip' => 'Reportes', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reportes / Reporte 1', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9002, 'name_' => 'Report_2', 'display_name' => 'Reporte 2', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_2', 'tooltip' => 'Reportes', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reportes / Reporte 2', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9003, 'name_' => 'Report_3', 'display_name' => 'Reporte 3', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_3', 'tooltip' => 'Reportes', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reportes / Reporte 3', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9004, 'name_' => 'Report_4', 'display_name' => 'Reporte 4', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_4', 'tooltip' => 'Reportes', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reportes / Reporte 4', 'menu_type_id' => 2]);
        DB::table('menu')->insert(['id' => 9005, 'name_' => 'Report_5', 'display_name' => 'Reporte 5', 'menu_dad_id' => 9000, 'link_command' => 'app/Reports/Report_5', 'tooltip' => 'Reportes', 'image_icon' => '', 'status_id' => 1, 'breadcrumb' => 'Reportes / Reporte 5', 'menu_type_id' => 2]);
    }
}
